### ISSUE TITLE
Implement Logger

### ISSUE THREAD

**Issue by 2Cubed** [CactusBot/CactusBot#2]
https://docs.python.org/3/library/logging.html
https://docs.python.org/3/howto/logging.html

**Comment by Innectic** [comment]
Oops thought you could put multiple people to it.

**Comment by Innectic** [comment]
Taken care of in this commit: [https://github.com/CactusBot/CactusBot/commit/3d6345c5f3de6cbde996386d46a7842fa6ba1ce0](url)
