### ISSUE TITLE
%ARG[n/s]% variable with modifiers don't produce responses when no arguments are present

### ISSUE THREAD

**Issue by Innectic** [CactusBot/CactusBot#240]
`!command add testing %ARGS|reverse%`
`!testing`

**Comment by 2Cubed** [comment]
I'm not entirely sure what the issue is...
![image](https://cloud.githubusercontent.com/assets/12002323/23584333/a280aaf8-012c-11e7-8684-6af465bce3cc.png)

**Comment by 2Cubed** [comment]
Done in #246.
