### ISSUE TITLE
Finish unit tests

### ISSUE THREAD

**Issue by Innectic** [CactusBot/CactusBot#241]
We're still missing unit tests for lots of major components of the bot, and most commands.

**Comment by 2Cubed** [comment]
Parameter-based testing started on `test/property-based`.

**Comment by 2Cubed** [comment]
Let's try to get Coveralls code coverage to at least 80%. (We should shoot for 100% one day™, but having less than 80% isn't really acceptable.)

**Comment by 2Cubed** [comment]
Hit 92% in #296. Done! :tada:
