### ISSUE TITLE
join/leave announcements not working.

### ISSUE THREAD

**Issue by Alkali-Metal** [CactusBot/CactusBot#243]
## How to reproduce:
 - Turn on Join / Leave announcements
 - I just used my local hosted 0.3 bot to join/leave with a separate account and was checking to see if it would announce the entrance / leaving of the other bot/account

 ### Expected result:
  The bot announces when the user joins / leaves

### Actual result:
  Nothing happens

## Environment
Remote hosted bot

## Other Information
 :potato:

**Comment by Alkali-Metal** [comment]
(Adding image proof) 
![image](https://cloud.githubusercontent.com/assets/20218935/23584024/50562380-0112-11e7-85a9-33be863dd360.png)

**Comment by RPiAwesomeness** [comment]
We were unable to reproduce this, so for now this issue is going to be closed. Feel free to let us know if it reoccurs!
