### ISSUE TITLE
%ARGS% default returns "Not enough arguments!"

### ISSUE THREAD

**Issue by 2Cubed** [CactusBot/CactusBot#247]
Defaults work with `%ARGN%`.
![image](https://cloud.githubusercontent.com/assets/12002323/23584586/7b29dd7e-0133-11e7-822e-6eebae0e6c6f.png)

Defaults are broken with `%ARGS%`.
![image](https://cloud.githubusercontent.com/assets/12002323/23584584/733a6bd8-0133-11e7-952b-a8893d947918.png)

**Comment by Innectic** [comment]
We don't have defaults

**Comment by 2Cubed** [comment]
We do... look at my screenshots. :stuck_out_tongue:

**Comment by Innectic** [comment]
When were these even added? I don't remember seeing a pullreq or anything O_O

**Comment by 2Cubed** [comment]
Alongside modifiers, I think?

**Comment by 2Cubed** [comment]
Fixed in #295.
