### ISSUE TITLE
Move MessagePackets to raw strings

### ISSUE THREAD

**Issue by 2Cubed** [CactusBot/CactusBot#248]
Currently, we store `MessagePackets`, comprising of components which each contain `data`, `text`, and `type`.

```json
{
  "data": "Hello, world!",
  "text": "Hello, world!",
  "type": "text"
}
```

While this is a good format, it makes storage errors due to parsing very easy. (For example, if stored with the incorrect `link` type instead of `url`, the component will not be seen as a URL until the packet is re-added.)

Instead, we should store plaintext, and use helper functions to perform operations on it.

For example, rather than storing `("Cactus! ", "Cactus! ", "text"), ("🌵", "🌵", "emoji")`, we would simply store `"Cactus! 🌵"`. Methods of `MessagePacket` would still perform the same operations, but using this simpler format, rather than the nested components.

This will require far less mass updating of data for schema upgrades; if we currently wanted to make `variable` a valid `type` currently, for example, we would have to change every stored `MessagePacket` in the database. We also gain access to Python's powerful string processing tools, without having to use `.text` or writing custom versions of the methods.

**Comment by Innectic** [comment]
How would we use this?

**Comment by Innectic** [comment]
How would we use this to create cross-service stuff?

**Comment by 2Cubed** [comment]
@Innectic In the same way that our current format works.

If a user on Beam sends `Hello! :cactus` and we receive a Beam-formatted packet, we then convert it to reflect the standard we set for these text-based packets. (`Hello! 🌵`)

**Comment by 2Cubed** [comment]
Unicode emoji filtering is "impossible", unless you have a giant list of all Unicode emoji somewhere. Maybe use a custom regex? The following seems like it should work, without getting in the way of anything that would show up in a regular message (`Favorite food: potato`, `12:56:43pm`, etc.).

```
:[a-zA-Z]\w+:
```

**Comment by 2Cubed** [comment]
Closed in favor of a standard CactusBot format.
