### ISSUE TITLE
config.template.py and INSTALL.md are inconsistent

### ISSUE THREAD

**Issue by willow-bohlen** [CactusBot/CactusBot#251]
In `INSTALL.md`, it says this:
`Next, open 'config.py' with your favorite text editor, and set 
'USERNAME' and 'PASSWORD' to the bot's credentials, and set 'CHANNEL' to your channel's name.`

However, the `config.template.py` doesn't have 'USERNAME' or 'PASSWORD', only this:

`TOKEN = "OAuth_Token"
CHANNEL = "ChannelName"

API_TOKEN = "CactusAPI_Token"
API_PASSWORD = "CactusAPI_Password"
API_URL = "https://cactus.exoz.one/api/v1/"`

Just a simple inconsistency that can be easily fixed.

**Comment by Innectic** [comment]
Ah, seems that I forgot to update the install instructions when I implemented OAuth. Fixing now :)

**Comment by willow-bohlen** [comment]
@Innectic is da real mvp
