### ISSUE TITLE
Switch handlers to asynchronous generators

### ISSUE THREAD

**Issue by willow-bohlen** [CactusBot/CactusBot#253]
I was just looking around in the code, and noticed this at line 88 of cactusbot/handler.py:

`# TODO: In Python 3.6, with asynchronous generators:`
`# yield packet`

Well we're in 3.6 now, so go for it.

**Comment by Innectic** [comment]
This can't be done yet. We can't assume that everyone is always on 3.6, because it's too new. This is being pushed to 0.5.

**Comment by willow-bohlen** [comment]
fiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiinnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnneeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by Innectic** [comment]
Merged into #254
