### ISSUE TITLE
!multi with no arguments has an unhelpful help message

### ISSUE THREAD

**Issue by RPiAwesomeness** [CactusBot/CactusBot#264]
## What is the issue?
Running just `!multi` returns `Not enough arguments. <>`. This is rather unhelpful and should be fixed. If it can't be done programmatically, then we'll have to hard-code it.

**Comment by 2Cubed** [comment]
`command.py` needs to include support for `*args` in `message`.

**Comment by 2Cubed** [comment]
Fixed in #281.

![image](https://cloud.githubusercontent.com/assets/12002323/24424845/0df323be-13d0-11e7-9a2f-f211ce3a16e0.png)
