### ISSUE TITLE
Magic command targeted responses

### ISSUE THREAD

**Issue by Innectic** [CactusBot/CactusBot#299]
Adding `target=True` to the `@Command.command` decorator, should make the command whisper the response back, and delete the original message.

**Comment by 2Cubed** [comment]
Good call! While you can use the following, `target=True` would be far cleaner.

```python
@Command.command()
async def thing(self, *, packet: "packet"):
    return MessagePacket("Hi!", target=packet.user)
```
```python
@Command.command(target=True)
async def thing(self):
    return "Hi!"
```

**Comment by Innectic** [comment]
@2Cubed Good point, however, importing message packet for everything is just meh /shrug
