### ISSUE TITLE
Bot ignores rate limits

### ISSUE THREAD

**Issue by 2Cubed** [CactusBot/CactusBot#308]
The bot ignores rate limits, trying to send messages whenever they are received. This especially impacts responses that are split over multiple chat messages.

**Comment by Innectic** [comment]
Important thing: Each service handler needs to implement this some how. Different services have different rate limits.

**Comment by 2Cubed** [comment]
We should probably have a generalized ratelimit method somewhere in the `WebSocket` class, which can either be used or ignored by the individual services.

**Comment by Innectic** [comment]
It shouldn't be able to be ignored. It should be required.

**Comment by Alkali-Metal** [comment]
Maybe make it so that if a service rate limit isn't supplied by the handler (Or whatever would handle it) it then falls back to the default one and can't be bypassed?

**Comment by 2Cubed** [comment]
Issue moved to [CactusDev/Aerophyl #9](https://github.com/CactusDev/Aerophyl/issues/9) via [**ZenHub**](https://www.zenhub.com/)
