### ISSUE TITLE
docs: nav column title says "Python" rather than "CactusBot"

### ISSUE THREAD

**Issue by eliotb** [CactusBot/CactusBot#312]
## A very minor problem on readthedocs

Here https://cactusbot.readthedocs.io/en/stable/contents.html#

The page title is "Python documentation" and the title at the top of the nav column is "Python".

They should say "CactusBot"

Its not obvious to me where this is set in the documentation files...

**Comment by Innectic** [comment]
Hi! Thank you for reporting this to us!

At this time, we will be rewriting our entire documentation, as the bot is currently undergoing a rewrite.

We appreciate this being reported anyways :)
